# Reference: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/code/typescript"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      # We have newer versions but need to stay on the 0.x line
      - dependency-name: "cdk-dynamo-table-viewer"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "maven"
    directory: "/code/java"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "nuget"
    directory: "/code/csharp"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/code/python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/cdkworkshop.com"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
