baseURL = "https://cdkworkshop.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "AWS CDK Workshop"
theme = "hugo-book"
uglyurls = true
sectionPagesMenu = "main"

hasCJKLanguage = true

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/english"
  [languages.ja]
    languageName = "日本語"
    contentDir = "content/japanese"

[markup]
[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.parser.attribute]
block = true
title = true

[markup.tableOfContents]
  startLevel = 1

  [markup.highlight]
    noClasses = false

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = false

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be logo.png
  BookLogo = 'images/favicon.png'

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  # BookMenuBundle = '/menu'

  # (Optional, default docs) Specify root page to render child pages as menu.
  # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'
  BookSection = '/'

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/aws-samples/aws-cdk-intro-workshop'

  # (Optional, default 'commit') Specifies commit portion of the link to the page's last modified
  # commit hash for 'doc' page type.
  # Requires 'BookRepo' param.
  # Value used to construct a URL consisting of BookRepo/BookCommitPath/<commit-hash>
  # Github uses 'commit', Bitbucket uses 'commits'
  BookCommitPath = 'commit'

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Edit path must point to root directory of repo.
  BookEditPath = 'edit/master/workshop'

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = 'January 2, 2006'

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  # Configuration for indexing can be adjusted in i18n folder per language.
  BookSearch = true

  # (Optional, default true) Enables comments template on pages
  # By default partals/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  # BookComments = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
  # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
  # Theme will print warning if page referenced in markdown does not exists.
  BookPortableLinks = false

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables service worker that caches visited pages and resources for offline use.
  BookServiceWorker = false

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables a drop-down menu for translations only if a translation is present.
  BookTranslatedOnly = false



[menu]

[[menu.after]]
name = "CDK on GitHub"
url = "https://github.com/awslabs/aws-cdk"
weight = 2

[[menu.after]]
name = "CDK on StackOverflow"
url = "https://stackoverflow.com/questions/tagged/aws-cdk"
weight = 3

[[menu.after]]
name = "CDK on Gitter"
identifier = "gt"
url = "https://gitter.im/awslabs/aws-cdk"
weight = 4

[[menu.after]]
name = "CDK Live on YouTube"
identifier = "gt"
url = "https://bit.ly/cdk-live"
weight = 5

[[menu.after]]
name = "Submit a correction"
url = "https://github.com/aws-samples/aws-cdk-intro-workshop"
weight = 1


[outputs]
home = [ "HTML", "AMP", "RSS"]
page = [ "HTML", "AMP"]
